# Generated by Django 5.0.6 on 2026-06-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_chatsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardtag',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='waiting_parrot_answer',
        ),
        migrations.AddField(
            model_name='businesscard',
            name='extraction_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='extraction_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='normalized_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='raw_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='source_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_query',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lineuser',
            name='picture_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lineuser',
            name='status_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='phone',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddIndex(
            model_name='businesscard',
            index=models.Index(fields=['source_message_id'], name='cards_busin_source__3f2aab_idx'),
        ),
        migrations.AddIndex(
            model_name='businesscard',
            index=models.Index(fields=['title'], name='cards_busin_title_e02aae_idx'),
        ),
    ]
