# Generated by Django 5.0.6 on 2026-02-11 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardInputSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("name", "Name"),
                            ("company", "Company"),
                            ("title", "Title"),
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("done", "Done"),
                        ],
                        default="name",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_sessions",
                        to="cards.businesscard",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_session",
                        to="cards.lineuser",
                    ),
                ),
            ],
        ),
    ]
