# Generated by Django 5.0.6 on 2026-02-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_cardinputsession"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CardInputSession",
        ),
    ]
